version: '3'

services:
#  app:
#    image: 'docker-spring-boot-postgres:latest'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - pgdbRating
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdbRating:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=12345
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    ports:
#      - "8080:8080"
          
  pgdbRating:
    image: postgres:12.1-alpine
    container_name: pgdbrating
    ports:
      - "5432:5432"
    volumes:
      - "postgres_rating:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "ratingservice"
      PGDATA: "/pgdata"
volumes:
  postgres_rating:
    driver: local
